# Generated by Django 6.0.4 on 2026-04-09 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Imię i nazwisko')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='Firma')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nazwa')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('color', models.CharField(default='#1d4ed8', max_length=7, verbose_name='Kolor')),
                ('sort_order', models.PositiveSmallIntegerField(default=1, verbose_name='Kolejność')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Zamknięty')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statusy',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('reservation', 'Rezerwacja'), ('order', 'Zamówienie')], default='reservation', max_length=20, verbose_name='Typ')),
                ('title', models.CharField(max_length=150, verbose_name='Tytuł')),
                ('service_name', models.CharField(max_length=150, verbose_name='Usługa / produkt')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Termin')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ilość')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kwota')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi od klienta')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notatki wewnętrzne')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.client', verbose_name='Klient')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Dodał')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orders', to=settings.AUTH_USER_MODEL, verbose_name='Ostatnio zmienił')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.orderstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Zamówienie / rezerwacja',
                'verbose_name_plural': 'Zamówienia / rezerwacje',
                'ordering': ['status__sort_order', '-created_at'],
            },
        ),
    ]
